services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL=sqlite:////./app/data/sql_app.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  sqlite_data: